version: "3"

services:
  datastore-dsui:
    image: joemugen/datastore-dsui
    environment:
      - DATASTORE_PROJECT_ID=project-test
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081
    ports:
      - "8081:8081"
      - "3000:3000"
