version: "3"

services:
  datastore-dsui:
    container_name: datastore
    restart: always
    # image: joemugen/datastore-dsui
    build:
      context: ""
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./imports:/opt/imports
      - ./datas:/opt/data
    ports:
      - "${DATASTORE_PORT:-8081}:${DATASTORE_PORT:-8081}"
      - "${GUI_PORT:-3000}:${GUI_PORT:-3000}"
volumes:
  imports:
  datas: