version: "3"

services:
  datastore-dsui:
    restart: always
    image: joemugen/datastore-dsui
    environment:
      - DATASTORE_PROJECT_ID=${DATASTORE_PROJECT_ID}
      - DATASTORE_LISTEN_ADDRESS=${DATASTORE_EMULATOR_HOST}
    ports:
      - "8081:8081"
      - "3000:3000"
